version: 2.1
orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          name: Download JDK 17
          command: |
            curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 17.0.7-jbr
            java --version      
      - checkout
      - android/run-tests:
          test-command: ./gradlew core:test
      - android/start-emulator-and-run-tests:
          avd-name: myavd
          no-window: false
          no-boot-anim: false
          system-image: system-images;android-29;default;x86
          disable-animations: false          
          restore-gradle-cache-prefix: v1a
          test-command: ./gradlew app:connectedAndroidTest
          max-tries: 1
      - android/save-gradle-cache:
          cache-prefix: v1a      
workflows:
  test:
    jobs:
      - test