version: 2.1
orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          command: |
            curl -s "https://get.sdkman.io" | bash
            sdk install java 17.0.7-jbr
            java --version      
      - checkout
      - android/run-tests:
          test-command: ./gradlew core:test
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator-and-run-tests:
          avd-name: myavd
          no-window: true
          no-boot-anim: false
          disable-animations: false          
          restore-gradle-cache-prefix: v1a
          test-command: ./gradlew app:connectedDebugAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v1a
workflows:
  test:
    jobs:
      - test