-keep public class net.sqlcipher.**{*;}
-keep public class net.sqlcipher.database.**{*;}
-keep class okhttp3.ResponseBody{*;}
-keep class com.android.tools.profiler.agent.okhttp.**{*;}
-ignorewarnings